# ===================================
#  Relation Behavior Config
# ===================================

videos:
    label: individuart.videogallery::lang.plugin.controllers.videos.relation.label
    view:
        list: $/individuart/videogallery/models/video/columns.yaml
        toolbarButtons: add|remove
    manage:
        list: $/individuart/videogallery/models/video/columns.yaml
        recordsPerPage: 10