# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: individuart.videogallery::lang.plugin.controllers.playlists.name

# Model Form Field configuration
form: $/individuart/videogallery/models/playlist/fields.yaml

# Model Class name
modelClass: Individuart\Videogallery\Models\Playlist

# Default redirect location
defaultRedirect: individuart/videogallery/playlists

# Create page
create:
    title: individuart.videogallery::lang.plugin.controllers.playlists.create.title
    redirect: individuart/videogallery/playlists/update/:id
    redirectClose: individuart/videogallery/playlists

# Update page
update:
    title: individuart.videogallery::lang.plugin.controllers.playlists.update.title
    redirect: individuart/videogallery/playlists
    redirectClose: individuart/videogallery/playlists

# Preview page
preview:
    title: Preview Playlist
