<?php

namespace individuart\videogallery\tests\components;

use Individuart\Videogallery\Components\SinglePlaylist;
use PluginTestCase;
use Individuart\Videogallery\Models\Playlist;
use Individuart\Videogallery\Models\Video;

/**
 * Class VideoListTest
 *
 * @package individuart\videogallery\tests\components
 *
 */
class SinglePlaylistTest extends PluginTestCase
{
    /** @var Video */
    protected $video;
    /** @var Playlist */
    protected $playlist;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->video = Video::create([
            'title' => 'Final Fantasy VI',
            'yt_watch' => 'sAyb0Arwy8g',
            'published' => true
        ]);

        /** @var Playlist $playlist */
        $this->playlist = Playlist::create([
            'name' => 'test'
        ]);

        $this->playlist->videos()->attach($this->video->id);
    }


    /**
     * @test
     */
    public function can_create_and_run_video_list_having_videos()
    {
        $videoList = new SinglePlaylist();
        $videoList->setProperty('playlist', 1);

        // Void return. We just expect that it doesn't crash
        $videoList->onRun();
    }

    /**
     * @test
     */
    public function component_details_is_properly_defined()
    {
        $details = (new SinglePlaylist)->componentDetails();

        $this->assertArrayHasKey('name', $details);
        $this->assertArrayHasKey('description', $details);
    }

    /**
     * @test
     */
    public function playlist_options()
    {
        $options = (new SinglePlaylist)->getPlaylistOptions();

        $this->assertCount(1, $options);
    }

    /**
     * @test
     */
    public function properly_sets_error_true_when_cant_find_gallery()
    {
        $videoList = new SinglePlaylist();

        $videoList->onRun();
    }
}
