# ===================================
#  Relation Behavior Config
# ===================================

playlists:
    label: individuart.videogallery::lang.plugin.controllers.playlists.relation.label
    view:
        list: $/individuart/videogallery/models/playlist/columns.yaml
        toolbarButtons: add|remove
    manage:
        list: $/individuart/videogallery/models/playlist/columns.yaml
        recordsPerPage: 10