# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: individuart.videogallery::lang.plugin.controllers.videos.name

# Model Form Field configuration
form: $/individuart/videogallery/models/video/fields.yaml

# Model Class name
modelClass: Individuart\Videogallery\Models\Video

# Default redirect location
defaultRedirect: individuart/videogallery/videos

# Create page
create:
    title: individuart.videogallery::lang.plugin.controllers.videos.create.title
    redirect: individuart/videogallery/videos/update/:id
    redirectClose: individuart/videogallery/videos

# Update page
update:
    title: individuart.videogallery::lang.plugin.controllers.videos.update.title
    redirect: individuart/videogallery/videos
    redirectClose: individuart/videogallery/videos

# Preview page
preview:
    title: Preview Video
